import type { IncidentContext } from "@/lib/types";

export type IncidentFieldType = "text" | "textarea" | "select" | "datetime-local";

export type IncidentField = {
  id: string;
  label: string;
  type: IncidentFieldType;
  required?: boolean;
  placeholder?: string;
  hint?: string;
  options?: string[];
};

export type IncidentScenario = {
  id: string;
  name: string;
  category: string;
  description: string;
  objective: string;
  focus: string;
  targetFieldIds: string[];
  timeFieldId?: string;
  fields: IncidentField[];
};

const timeOptions = [
  "Within the last hour",
  "Within the last 4 hours",
  "Within the last 24 hours",
  "Within the last 7 days",
  "More than 7 days ago",
  "Unknown",
];

const detectedAtField = (id = "detected_at"): IncidentField => ({
  id,
  label: "When was it detected?",
  type: "datetime-local",
  hint: "Use the approximate detection time if the exact time is unknown.",
});

export const INCIDENT_SCENARIOS: IncidentScenario[] = [
  {
    id: "server-compromise",
    name: "Server compromise",
    category: "Endpoint / Server",
    description: "Investigate a suspected compromise of a production or internal server.",
    objective: "Determine whether the server was compromised, how access was obtained, what activity occurred, and whether additional systems or accounts were involved.",
    focus: "Authentication, privilege escalation, process execution, persistence, network connections, lateral movement, and post-compromise activity.",
    targetFieldIds: ["hostname", "server_ip", "primary_user"],
    timeFieldId: "detected_at",
    fields: [
      { id: "hostname", label: "Hostname / asset name", type: "text", required: true, placeholder: "e.g. WEB-PROD-01" },
      { id: "server_ip", label: "Server IP", type: "text", placeholder: "e.g. 10.20.30.40" },
      { id: "os", label: "Operating system", type: "text", placeholder: "e.g. Ubuntu 24.04 / Windows Server 2022" },
      { id: "primary_user", label: "Known user / service account", type: "text" },
      detectedAtField(),
      { id: "initial_indicator", label: "Initial indicator", type: "textarea", required: true, placeholder: "What was observed first?" },
      { id: "suspected_access", label: "Suspected access method", type: "select", options: ["Remote login", "Stolen credentials", "Exploited vulnerability", "Malware", "Web application", "Unknown"] },
      { id: "suspicious_processes", label: "Suspicious processes / commands", type: "textarea" },
      { id: "network_indicators", label: "Known suspicious IPs, domains, or connections", type: "textarea" },
      { id: "actions_taken", label: "Actions already taken by humans", type: "textarea", placeholder: "e.g. host isolated, account disabled, credentials reset" },
    ],
  },
  {
    id: "pc-compromise",
    name: "PC / workstation compromise",
    category: "Endpoint",
    description: "Investigate a suspected compromise of an employee workstation or laptop.",
    objective: "Determine whether the endpoint was compromised, identify the initial access vector, and establish what accounts, processes, files, and network activity were affected.",
    focus: "User logons, endpoint telemetry, process execution, downloads, persistence, network activity, and credential use.",
    targetFieldIds: ["hostname", "username", "endpoint_ip"],
    timeFieldId: "detected_at",
    fields: [
      { id: "hostname", label: "Hostname / device name", type: "text", required: true },
      { id: "username", label: "Primary user", type: "text", required: true },
      { id: "endpoint_ip", label: "Device IP", type: "text" },
      { id: "os", label: "Operating system", type: "text" },
      { id: "location", label: "Device / user location", type: "text" },
      detectedAtField(),
      { id: "symptoms", label: "Observed symptoms", type: "textarea", required: true, placeholder: "Unexpected pop-ups, antivirus alert, slow system, unknown process, etc." },
      { id: "suspicious_file", label: "Suspicious file / application / URL", type: "textarea" },
      { id: "known_download", label: "Known download or attachment involved?", type: "select", options: ["Yes", "No", "Unknown"] },
      { id: "actions_taken", label: "Actions already taken by humans", type: "textarea" },
    ],
  },
  {
    id: "phishing",
    name: "Phishing",
    category: "Email",
    description: "Investigate a suspicious email or phishing campaign and identify impacted users.",
    objective: "Determine whether the message was malicious, who received it, which users interacted with it, and whether credentials or hosts may have been compromised.",
    focus: "Email delivery, sender infrastructure, URLs, attachments, user interaction, authentication activity, and campaign scope.",
    targetFieldIds: ["recipient", "sender", "phishing_domain"],
    timeFieldId: "received_at",
    fields: [
      { id: "recipient", label: "Recipient / reported user", type: "text", required: true },
      { id: "sender", label: "Sender address", type: "text", required: true, placeholder: "attacker@example.com" },
      { id: "subject", label: "Email subject", type: "text" },
      { id: "received_at", label: "When was the email received?", type: "datetime-local" },
      { id: "phishing_domain", label: "URL / phishing domain", type: "text" },
      { id: "attachment", label: "Attachment name / type", type: "text" },
      { id: "clicked", label: "Did the user click a link?", type: "select", options: ["Yes", "No", "Unknown"] },
      { id: "submitted_credentials", label: "Did the user submit credentials or sensitive data?", type: "select", options: ["Yes", "No", "Unknown"] },
      { id: "other_recipients", label: "Other known recipients", type: "textarea" },
      { id: "headers_available", label: "Email headers or message trace available?", type: "select", options: ["Yes", "No", "Unknown"] },
    ],
  },
  {
    id: "business-email-compromise",
    name: "Business email compromise",
    category: "Email / Identity",
    description: "Investigate suspected mailbox takeover, impersonation, or payment fraud using email.",
    objective: "Determine whether a mailbox or identity was compromised, how access occurred, what forwarding or rule changes happened, and which communications were affected.",
    focus: "Mailbox logins, MFA, inbox rules, forwarding, OAuth/application access, suspicious sender activity, and related account activity.",
    targetFieldIds: ["mailbox", "suspicious_source_ip", "impersonated_identity"],
    timeFieldId: "detected_at",
    fields: [
      { id: "mailbox", label: "Affected mailbox", type: "text", required: true },
      { id: "impersonated_identity", label: "Impersonated executive / vendor / identity", type: "text" },
      { id: "suspicious_source_ip", label: "Known suspicious source IP", type: "text" },
      { id: "detected_at", label: "When was it detected?", type: "datetime-local" },
      { id: "financial_context", label: "Financial / payment context", type: "textarea", placeholder: "Invoice, payment change, bank detail change, gift card request, etc." },
      { id: "mailbox_changes", label: "Known mailbox rule / forwarding changes", type: "textarea" },
      { id: "oauth_access", label: "Suspicious OAuth / application access?", type: "select", options: ["Yes", "No", "Unknown"] },
      { id: "affected_users", label: "Other affected users or mailboxes", type: "textarea" },
      { id: "actions_taken", label: "Actions already taken by humans", type: "textarea" },
    ],
  },
  {
    id: "credential-compromise",
    name: "Credential compromise",
    category: "Identity",
    description: "Investigate suspected theft or misuse of a corporate credential.",
    objective: "Determine whether a credential was abused, identify the source and scope of access, and find related authentication or post-authentication activity.",
    focus: "Authentication events, MFA, source IPs, geolocation, device posture, privilege, lateral movement, and account activity.",
    targetFieldIds: ["username", "source_ip"],
    timeFieldId: "detected_at",
    fields: [
      { id: "username", label: "Affected account", type: "text", required: true },
      { id: "account_type", label: "Account type", type: "select", options: ["Employee", "Privileged", "Service account", "Application account", "Unknown"] },
      { id: "source_ip", label: "Known suspicious source IP", type: "text" },
      { id: "detected_at", label: "When was it detected?", type: "datetime-local" },
      { id: "mfa_status", label: "MFA status", type: "select", options: ["Enabled", "Disabled", "Bypassed / challenged", "Unknown"] },
      { id: "suspected_source", label: "Suspected credential source", type: "select", options: ["Phishing", "Credential stuffing", "Malware", "Password reuse", "Unknown"] },
      { id: "last_known_legitimate", label: "Last known legitimate activity", type: "textarea" },
      { id: "locations_ips", label: "Known unusual locations / IPs", type: "textarea" },
      { id: "password_changed", label: "Credential reset already performed?", type: "select", options: ["Yes", "No", "Unknown"] },
    ],
  },
  {
    id: "malware",
    name: "Malware infection",
    category: "Endpoint / Malware",
    description: "Investigate a suspected malware infection on an endpoint or server.",
    objective: "Determine the malware execution timeline, initial access indicators, affected host and user, persistence, network activity, and potential spread.",
    focus: "Process tree, file activity, hashes, downloads, persistence, DNS, network connections, and related hosts/users.",
    targetFieldIds: ["hostname", "username", "malware_hash"],
    timeFieldId: "detected_at",
    fields: [
      { id: "hostname", label: "Affected host", type: "text", required: true },
      { id: "username", label: "Affected user", type: "text" },
      { id: "malware_family", label: "Suspected malware family", type: "text" },
      { id: "malware_hash", label: "File hash", type: "text" },
      { id: "file_path", label: "Suspicious file path", type: "text" },
      { id: "detected_at", label: "When was it detected?", type: "datetime-local" },
      { id: "symptoms", label: "Symptoms / detections", type: "textarea", required: true },
      { id: "parent_process", label: "Known parent process / execution chain", type: "textarea" },
      { id: "network_activity", label: "Known suspicious network activity", type: "textarea" },
      { id: "actions_taken", label: "Actions already taken by humans", type: "textarea" },
    ],
  },
  {
    id: "ransomware",
    name: "Ransomware / destructive activity",
    category: "Malware / Availability",
    description: "Investigate suspected ransomware, mass encryption, or destructive activity.",
    objective: "Determine the initial affected system, the start of destructive activity, possible lateral movement, and the current scope of impact.",
    focus: "Mass file changes, process execution, account activity, lateral movement, backups, shares, and affected assets.",
    targetFieldIds: ["hostname", "username"],
    timeFieldId: "detected_at",
    fields: [
      { id: "hostname", label: "First known affected host", type: "text", required: true },
      { id: "username", label: "Known affected account", type: "text" },
      { id: "detected_at", label: "When was it detected?", type: "datetime-local" },
      { id: "ransom_note", label: "Ransom note / extension / malware name", type: "text" },
      { id: "encrypted_assets", label: "Known encrypted or unavailable assets", type: "textarea" },
      { id: "suspected_entry", label: "Suspected initial access", type: "select", options: ["Phishing", "Exposed service", "Stolen credentials", "Vulnerability", "Third party", "Unknown"] },
      { id: "lateral_movement", label: "Known lateral movement indicators", type: "textarea" },
      { id: "backup_impact", label: "Backup / recovery impact", type: "textarea" },
      { id: "actions_taken", label: "Actions already taken by humans", type: "textarea" },
    ],
  },
  {
    id: "web-application-compromise",
    name: "Web application compromise",
    category: "Application",
    description: "Investigate suspected compromise or abuse of a web application or API.",
    objective: "Determine whether the application was exploited, identify the relevant requests and attacker infrastructure, and establish affected hosts, accounts, or data.",
    focus: "HTTP requests, WAF/CDN telemetry, application errors, authentication, exploitation indicators, and post-exploitation activity.",
    targetFieldIds: ["application", "domain", "attacker_ip"],
    timeFieldId: "detected_at",
    fields: [
      { id: "application", label: "Application / service", type: "text", required: true },
      { id: "domain", label: "Domain / hostname", type: "text" },
      { id: "attacker_ip", label: "Known attacker / source IP", type: "text" },
      { id: "detected_at", label: "When was it detected?", type: "datetime-local" },
      { id: "endpoint", label: "Affected URL / API endpoint", type: "text" },
      { id: "cve", label: "Known CVE / vulnerability", type: "text" },
      { id: "suspicious_requests", label: "Suspicious request pattern", type: "textarea" },
      { id: "affected_server", label: "Known backend server / container", type: "text" },
      { id: "waf_activity", label: "WAF / CDN observations", type: "textarea" },
      { id: "data_concern", label: "Potential data access concern", type: "textarea" },
    ],
  },
  {
    id: "cloud-account-compromise",
    name: "Cloud account compromise",
    category: "Cloud / Identity",
    description: "Investigate suspicious use of an AWS, Azure, GCP, or other cloud identity.",
    objective: "Determine whether a cloud identity or credential was compromised, what API actions occurred, and which cloud resources may be affected.",
    focus: "Authentication, API activity, privilege changes, new resources, key usage, regions, source IPs, and persistence.",
    targetFieldIds: ["cloud_account", "source_ip", "resource"],
    timeFieldId: "detected_at",
    fields: [
      { id: "provider", label: "Cloud provider", type: "select", options: ["AWS", "Microsoft Azure", "Google Cloud", "Other"] },
      { id: "cloud_account", label: "Account / subscription / project", type: "text", required: true },
      { id: "identity", label: "Affected user / role / service account", type: "text" },
      { id: "source_ip", label: "Known source IP", type: "text" },
      { id: "resource", label: "Affected resource", type: "text" },
      { id: "detected_at", label: "When was it detected?", type: "datetime-local" },
      { id: "suspicious_api_calls", label: "Known suspicious API actions", type: "textarea" },
      { id: "regions", label: "Suspicious regions / locations", type: "textarea" },
      { id: "mfa", label: "MFA status", type: "select", options: ["Enabled", "Disabled", "Unknown"] },
      { id: "actions_taken", label: "Actions already taken by humans", type: "textarea" },
    ],
  },
  {
    id: "network-intrusion",
    name: "Network intrusion",
    category: "Network",
    description: "Investigate suspected unauthorized network access or lateral movement.",
    objective: "Determine the source, destination, protocol, timing, and scope of suspicious network activity and identify related hosts or accounts.",
    focus: "Firewall, NetFlow, proxy, IDS/IPS, DNS, remote access, scanning, lateral movement, and command-and-control indicators.",
    targetFieldIds: ["source_ip", "destination_ip", "destination_host"],
    timeFieldId: "detected_at",
    fields: [
      { id: "source_ip", label: "Source IP", type: "text", required: true },
      { id: "destination_ip", label: "Destination IP", type: "text" },
      { id: "destination_host", label: "Destination hostname", type: "text" },
      { id: "source_host", label: "Source hostname", type: "text" },
      { id: "protocol", label: "Protocol / port", type: "text" },
      { id: "sensor", label: "Detection source", type: "select", options: ["Firewall", "IDS/IPS", "NetFlow", "Proxy", "DNS", "EDR", "Other"] },
      { id: "detected_at", label: "When was it detected?", type: "datetime-local" },
      { id: "traffic_description", label: "Observed traffic / behavior", type: "textarea", required: true },
      { id: "payload_indicator", label: "Known payload / signature / domain", type: "textarea" },
      { id: "duration", label: "Approximate duration", type: "text" },
    ],
  },
  {
    id: "data-exfiltration",
    name: "Data exfiltration",
    category: "Data Security",
    description: "Investigate suspected unauthorized transfer of company data.",
    objective: "Determine what data may have left the environment, from which system and account, through which channel, and whether the activity is supported by telemetry.",
    focus: "Data access, file activity, database queries, outbound network traffic, cloud storage, email, and unusual transfers.",
    targetFieldIds: ["source_host", "username", "destination"],
    timeFieldId: "detected_at",
    fields: [
      { id: "source_host", label: "Source host / system", type: "text", required: true },
      { id: "username", label: "Account involved", type: "text" },
      { id: "destination", label: "Destination IP / domain / service", type: "text" },
      { id: "data_system", label: "Source data system", type: "text" },
      { id: "detected_at", label: "When was it detected?", type: "datetime-local" },
      { id: "data_type", label: "Type of data involved", type: "textarea" },
      { id: "transfer_channel", label: "Suspected transfer channel", type: "select", options: ["HTTPS", "SFTP / FTP", "Email", "Cloud storage", "Database", "USB / removable media", "Unknown"] },
      { id: "estimated_volume", label: "Estimated volume", type: "text" },
      { id: "classification", label: "Data classification", type: "text", placeholder: "Public / Internal / Confidential / Restricted" },
    ],
  },
  {
    id: "insider-threat",
    name: "Insider threat investigation",
    category: "User / Data",
    description: "Investigate unusual user activity that may indicate misuse or unauthorized data access.",
    objective: "Determine whether observed activity is unusual for the user and establish the relevant systems, data, timing, and destinations.",
    focus: "Authentication, endpoint activity, file access, cloud usage, data transfers, privilege, and unusual destinations.",
    targetFieldIds: ["username", "hostname"],
    timeFieldId: "detected_at",
    fields: [
      { id: "username", label: "User / account", type: "text", required: true },
      { id: "hostname", label: "Primary host", type: "text" },
      { id: "department", label: "Department / business context", type: "text" },
      { id: "detected_at", label: "When was it detected?", type: "datetime-local" },
      { id: "unusual_behavior", label: "Unusual behavior observed", type: "textarea", required: true },
      { id: "data_access", label: "Sensitive systems / data accessed", type: "textarea" },
      { id: "destination", label: "Unusual destination / service", type: "text" },
      { id: "expected_behavior", label: "Expected normal behavior", type: "textarea" },
      { id: "business_context", label: "Relevant business context", type: "textarea" },
    ],
  },
  {
    id: "privilege-escalation",
    name: "Privilege escalation",
    category: "Identity / Endpoint",
    description: "Investigate suspected unauthorized elevation of privileges.",
    objective: "Determine how privileges changed, what account or process performed the change, and what activity followed the elevation.",
    focus: "Authentication, process execution, group membership, sudo/admin activity, UAC, tokens, and subsequent access.",
    targetFieldIds: ["hostname", "username"],
    timeFieldId: "detected_at",
    fields: [
      { id: "hostname", label: "Host", type: "text", required: true },
      { id: "username", label: "Affected account", type: "text", required: true },
      { id: "previous_privilege", label: "Previous privilege level", type: "text" },
      { id: "new_privilege", label: "Observed new privilege", type: "text" },
      { id: "detected_at", label: "When was it detected?", type: "datetime-local" },
      { id: "suspected_method", label: "Suspected elevation method", type: "textarea" },
      { id: "process", label: "Process / parent process", type: "textarea" },
      { id: "cve", label: "Known CVE / exploit", type: "text" },
      { id: "follow_on_activity", label: "Activity after privilege change", type: "textarea" },
    ],
  },
  {
    id: "vpn-remote-access",
    name: "VPN / remote access compromise",
    category: "Remote Access",
    description: "Investigate suspicious VPN, remote desktop, SSH, or other remote access activity.",
    objective: "Determine whether remote access was legitimate, identify the source and authentication pattern, and establish what happened after access.",
    focus: "VPN/RDP/SSH authentication, MFA, source IPs, device identity, geographic anomalies, and post-login activity.",
    targetFieldIds: ["username", "source_ip", "gateway"],
    timeFieldId: "login_time",
    fields: [
      { id: "username", label: "User / account", type: "text", required: true },
      { id: "gateway", label: "VPN / remote access gateway", type: "text" },
      { id: "source_ip", label: "Source IP", type: "text" },
      { id: "device", label: "Device / hostname", type: "text" },
      { id: "login_time", label: "Suspicious login time", type: "datetime-local" },
      { id: "mfa", label: "MFA result", type: "select", options: ["Successful", "Failed", "Bypassed / unavailable", "Unknown"] },
      { id: "location", label: "Reported / observed location", type: "text" },
      { id: "session_activity", label: "Known session activity", type: "textarea" },
      { id: "expected_access", label: "Was the access expected?", type: "select", options: ["Yes", "No", "Unknown"] },
    ],
  },
  {
    id: "dns-beaconing",
    name: "Suspicious DNS / beaconing",
    category: "Network / DNS",
    description: "Investigate repeated or anomalous DNS activity that may indicate malware or command-and-control.",
    objective: "Determine whether DNS behavior is anomalous and whether it correlates with an infected host, process, or external infrastructure.",
    focus: "DNS queries, frequency, domains, resolved IPs, first-seen behavior, process attribution, and proxy/network telemetry.",
    targetFieldIds: ["hostname", "domain"],
    timeFieldId: "first_seen",
    fields: [
      { id: "hostname", label: "Affected host", type: "text", required: true },
      { id: "domain", label: "Suspicious domain", type: "text", required: true },
      { id: "resolver", label: "DNS resolver", type: "text" },
      { id: "first_seen", label: "First observed time", type: "datetime-local" },
      { id: "query_frequency", label: "Observed query frequency", type: "text" },
      { id: "resolved_ips", label: "Resolved IPs", type: "textarea" },
      { id: "domain_context", label: "Domain reputation / context", type: "textarea" },
      { id: "process", label: "Suspected generating process", type: "text" },
      { id: "proxy_activity", label: "Related proxy / outbound activity", type: "textarea" },
    ],
  },
  {
    id: "ddos-availability",
    name: "DDoS / availability incident",
    category: "Availability",
    description: "Investigate a denial-of-service, traffic flood, or significant service availability incident.",
    objective: "Establish the incident timeline, affected services, traffic characteristics, source distribution, and relevant infrastructure behavior.",
    focus: "Traffic volume, source IPs, HTTP status codes, WAF/CDN, load balancers, application errors, and regional impact.",
    targetFieldIds: ["service", "domain", "public_ip"],
    timeFieldId: "started_at",
    fields: [
      { id: "service", label: "Affected service", type: "text", required: true },
      { id: "domain", label: "Domain", type: "text" },
      { id: "public_ip", label: "Public IP", type: "text" },
      { id: "started_at", label: "Incident start time", type: "datetime-local" },
      { id: "symptoms", label: "Availability symptoms", type: "textarea", required: true },
      { id: "traffic_sources", label: "Known traffic sources / distribution", type: "textarea" },
      { id: "traffic_volume", label: "Traffic volume / request rate", type: "text" },
      { id: "affected_regions", label: "Affected regions", type: "text" },
      { id: "cdn_waf", label: "CDN / WAF / upstream observations", type: "textarea" },
      { id: "application_metrics", label: "Application / infrastructure metrics", type: "textarea" },
    ],
  },
  {
    id: "vulnerability-exploitation",
    name: "Vulnerability exploitation",
    category: "Vulnerability",
    description: "Investigate whether a known vulnerability was actually exploited.",
    objective: "Determine whether exploitation is supported by telemetry, identify the source and affected asset, and establish what happened after exploitation.",
    focus: "Exploit requests, vulnerable versions, WAF/IDS, process execution, authentication, and post-exploitation activity.",
    targetFieldIds: ["asset", "cve", "source_ip"],
    timeFieldId: "detected_at",
    fields: [
      { id: "asset", label: "Affected asset", type: "text", required: true },
      { id: "cve", label: "CVE / advisory", type: "text", required: true },
      { id: "source_ip", label: "Known source IP", type: "text" },
      { id: "detected_at", label: "When was it detected?", type: "datetime-local" },
      { id: "software_version", label: "Installed software version", type: "text" },
      { id: "exploitation_indicator", label: "Evidence suggesting exploitation", type: "textarea", required: true },
      { id: "endpoint", label: "Affected endpoint / URL / service", type: "text" },
      { id: "waf_ids", label: "WAF / IDS observations", type: "textarea" },
      { id: "follow_on_activity", label: "Known post-exploitation activity", type: "textarea" },
    ],
  },
  {
    id: "lost-stolen-device",
    name: "Lost / stolen device",
    category: "Physical / Endpoint",
    description: "Investigate a lost or stolen company device and any subsequent activity associated with it.",
    objective: "Determine the device's last known activity, whether it appears to have connected after the loss, and what corporate identities or data may be exposed.",
    focus: "Device identity, last authentication, network activity, MDM/EDR telemetry, account use, and data access.",
    targetFieldIds: ["hostname", "username", "serial_number"],
    timeFieldId: "lost_at",
    fields: [
      { id: "hostname", label: "Hostname / device name", type: "text", required: true },
      { id: "serial_number", label: "Asset / serial number", type: "text" },
      { id: "username", label: "Assigned user", type: "text", required: true },
      { id: "lost_at", label: "When was it lost / stolen?", type: "datetime-local" },
      { id: "last_seen_location", label: "Last known location", type: "text" },
      { id: "last_network", label: "Last known network / IP", type: "text" },
      { id: "mdm_status", label: "MDM / device status", type: "text" },
      { id: "data_on_device", label: "Sensitive data potentially stored locally", type: "textarea" },
      { id: "post_loss_activity", label: "Known activity after loss", type: "textarea" },
    ],
  },
  {
    id: "third-party-compromise",
    name: "Third-party / supplier compromise",
    category: "Third Party",
    description: "Investigate a security incident involving a vendor, partner, SaaS service, or external integration.",
    objective: "Determine whether the third-party incident affected company systems, identities, data, or integrations and identify the relevant timeline.",
    focus: "Vendor access, API/service accounts, authentication, network activity, data flows, changes, and shared infrastructure.",
    targetFieldIds: ["vendor", "integration", "affected_system"],
    timeFieldId: "detected_at",
    fields: [
      { id: "vendor", label: "Vendor / supplier", type: "text", required: true },
      { id: "integration", label: "Affected integration / service", type: "text" },
      { id: "affected_system", label: "Internal affected system", type: "text" },
      { id: "service_account", label: "Related service account / identity", type: "text" },
      { id: "detected_at", label: "When was it detected?", type: "datetime-local" },
      { id: "vendor_notice", label: "Vendor notification / incident information", type: "textarea", required: true },
      { id: "recent_changes", label: "Recent vendor / integration changes", type: "textarea" },
      { id: "indicators", label: "Observed internal indicators", type: "textarea" },
      { id: "data_exposure", label: "Potential data exposure", type: "textarea" },
    ],
  },
  {
    id: "security-control-tampering",
    name: "Security control tampering",
    category: "Defense Evasion",
    description: "Investigate suspected disabling, modification, or bypass of a security control.",
    objective: "Determine what security control changed, who or what changed it, when it happened, and whether suspicious activity followed.",
    focus: "Administrative changes, service state, configuration, audit logs, endpoint controls, monitoring gaps, and subsequent activity.",
    targetFieldIds: ["hostname", "account", "control"],
    timeFieldId: "changed_at",
    fields: [
      { id: "control", label: "Security control", type: "text", required: true, placeholder: "EDR, AV, firewall, logging, MFA, audit policy, etc." },
      { id: "hostname", label: "Affected host / system", type: "text" },
      { id: "account", label: "Account involved", type: "text" },
      { id: "changed_at", label: "When was the change observed?", type: "datetime-local" },
      { id: "config_change", label: "Observed configuration / state change", type: "textarea", required: true },
      { id: "process", label: "Service / process involved", type: "text" },
      { id: "admin_context", label: "Expected administrative context", type: "textarea" },
      { id: "monitoring_impact", label: "Potential monitoring gap created", type: "textarea" },
      { id: "follow_on_activity", label: "Activity after the change", type: "textarea" },
    ],
  },
  {
    id: "unauthorized-access",
    name: "Unauthorized access",
    category: "Access Control",
    description: "Investigate access to a system, application, or data store that appears unauthorized.",
    objective: "Determine whether the access was legitimate, identify the account and source, and establish what actions occurred after access.",
    focus: "Authentication, authorization, source IP, application activity, privilege, and related data access.",
    targetFieldIds: ["system", "username", "source_ip"],
    timeFieldId: "access_time",
    fields: [
      { id: "system", label: "System / application", type: "text", required: true },
      { id: "username", label: "Account used", type: "text", required: true },
      { id: "source_ip", label: "Source IP", type: "text" },
      { id: "access_time", label: "Approximate access time", type: "datetime-local" },
      { id: "expected_access", label: "Expected access pattern", type: "textarea" },
      { id: "observed_actions", label: "Observed actions", type: "textarea", required: true },
      { id: "location", label: "Observed location / device", type: "text" },
      { id: "authentication", label: "Authentication method", type: "text" },
      { id: "data_accessed", label: "Known data / records accessed", type: "textarea" },
    ],
  },
  {
    id: "email-account-compromise",
    name: "Email account takeover",
    category: "Identity / Email",
    description: "Investigate suspected compromise of an individual mailbox independent of a broader BEC scenario.",
    objective: "Determine whether the mailbox was accessed by an unauthorized party and identify login, rule, forwarding, and message activity.",
    focus: "Mailbox sign-ins, MFA, forwarding rules, inbox rules, OAuth access, suspicious messages, and source IPs.",
    targetFieldIds: ["mailbox", "source_ip"],
    timeFieldId: "detected_at",
    fields: [
      { id: "mailbox", label: "Affected mailbox", type: "text", required: true },
      { id: "source_ip", label: "Known suspicious IP", type: "text" },
      { id: "detected_at", label: "When was it detected?", type: "datetime-local" },
      { id: "mfa", label: "MFA status", type: "select", options: ["Enabled", "Disabled", "Unknown"] },
      { id: "login_anomaly", label: "Suspicious login pattern", type: "textarea", required: true },
      { id: "rules_forwarding", label: "Rules / forwarding changes", type: "textarea" },
      { id: "oauth", label: "Suspicious application / OAuth access", type: "textarea" },
      { id: "messages_sent", label: "Suspicious outbound messages", type: "textarea" },
      { id: "actions_taken", label: "Actions already taken by humans", type: "textarea" },
    ],
  },
  {
    id: "api-key-compromise",
    name: "API key / service account compromise",
    category: "Application / Identity",
    description: "Investigate suspected misuse of an API key, token, bot account, or service identity.",
    objective: "Determine whether a service identity was abused, from which source, against which services, and whether persistence or privilege changes occurred.",
    focus: "Authentication, API calls, source IPs, key usage, privilege, application identity, and unusual resources.",
    targetFieldIds: ["service_identity", "source_ip", "application"],
    timeFieldId: "detected_at",
    fields: [
      { id: "service_identity", label: "API key / service identity", type: "text", required: true },
      { id: "application", label: "Application using the identity", type: "text" },
      { id: "source_ip", label: "Known source IP", type: "text" },
      { id: "detected_at", label: "When was it detected?", type: "datetime-local" },
      { id: "normal_usage", label: "Normal expected usage", type: "textarea" },
      { id: "suspicious_calls", label: "Suspicious API calls / resources", type: "textarea", required: true },
      { id: "privilege", label: "Known privilege level", type: "text" },
      { id: "rotation", label: "Key rotated / revoked already?", type: "select", options: ["Yes", "No", "Unknown"] },
    ],
  },
  {
    id: "database-compromise",
    name: "Database compromise / suspicious DB activity",
    category: "Data / Database",
    description: "Investigate suspicious database authentication, queries, configuration changes, or data access.",
    objective: "Determine whether database access or changes were unauthorized and establish affected accounts, queries, records, and source systems.",
    focus: "Database authentication, query activity, privileged operations, schema changes, data access, and source hosts.",
    targetFieldIds: ["database", "db_user", "source_host"],
    timeFieldId: "detected_at",
    fields: [
      { id: "database", label: "Database / cluster", type: "text", required: true },
      { id: "db_user", label: "Database account", type: "text" },
      { id: "source_host", label: "Source host / application", type: "text" },
      { id: "detected_at", label: "When was it detected?", type: "datetime-local" },
      { id: "query_indicator", label: "Suspicious query / operation", type: "textarea", required: true },
      { id: "data_scope", label: "Potentially affected tables / data", type: "textarea" },
      { id: "schema_changes", label: "Schema / permission changes", type: "textarea" },
      { id: "application_context", label: "Expected application behavior", type: "textarea" },
    ],
  },
  {
    id: "suspicious-file-download",
    name: "Suspicious file download / execution",
    category: "Endpoint / Web",
    description: "Investigate a suspicious file, download, script, or payload observed on a company endpoint.",
    objective: "Determine the origin, execution chain, affected host and user, and any subsequent network or persistence activity.",
    focus: "Browser/proxy telemetry, download source, file metadata, process execution, hashes, and network activity.",
    targetFieldIds: ["hostname", "username", "url"],
    timeFieldId: "downloaded_at",
    fields: [
      { id: "hostname", label: "Host", type: "text", required: true },
      { id: "username", label: "User", type: "text" },
      { id: "url", label: "Download URL / domain", type: "text" },
      { id: "downloaded_at", label: "Download time", type: "datetime-local" },
      { id: "filename", label: "Filename", type: "text" },
      { id: "hash", label: "File hash", type: "text" },
      { id: "browser", label: "Browser / application involved", type: "text" },
      { id: "executed", label: "Was it executed?", type: "select", options: ["Yes", "No", "Unknown"] },
      { id: "parent_process", label: "Known execution chain", type: "textarea" },
    ],
  },
  {
    id: "insufficiently-attributed-alert",
    name: "Security alert without clear attribution",
    category: "General",
    description: "Use this when a security signal exists but the affected entity or incident type is still unclear.",
    objective: "Determine whether the signal is security-relevant, identify the affected entity, and establish the smallest useful investigation scope.",
    focus: "Initial triage, entity discovery, timeline, related alerts, and corroborating telemetry.",
    targetFieldIds: ["entity"],
    timeFieldId: "detected_at",
    fields: [
      { id: "entity", label: "Known entity / indicator", type: "text", required: true, placeholder: "Host, user, IP, domain, event ID, URL, hash, etc." },
      { id: "detected_at", label: "Approximate detection time", type: "datetime-local" },
      { id: "source", label: "How was it reported?", type: "text" },
      { id: "initial_indicator", label: "Initial observation", type: "textarea", required: true },
      { id: "related_entities", label: "Other known entities", type: "textarea" },
      { id: "business_context", label: "Relevant business context", type: "textarea" },
    ],
  },
];

export function getIncidentScenario(id: string): IncidentScenario | undefined {
  return INCIDENT_SCENARIOS.find((scenario) => scenario.id === id);
}

export function buildIncidentContext(
  scenario: IncidentScenario,
  values: Record<string, string>,
): IncidentContext {
  const cleaned = Object.fromEntries(
    Object.entries(values)
      .map(([key, value]) => [key, value.trim()])
      .filter(([, value]) => Boolean(value)),
  );

  const target = scenario.targetFieldIds
    .map((fieldId) => cleaned[fieldId])
    .filter(Boolean)
    .join("; ");

  const summary = Object.entries(cleaned)
    .map(([fieldId, value]) => {
      const field = scenario.fields.find((item) => item.id === fieldId);
      return field ? field.label + ": " + value : fieldId + ": " + value;
    })
    .join("\n");

  return {
    scenarioId: scenario.id,
    scenarioName: scenario.name,
    objective: scenario.objective,
    focus: scenario.focus,
    target,
    detectedAt: scenario.timeFieldId ? cleaned[scenario.timeFieldId] : undefined,
    summary,
    values: cleaned,
    submittedAt: new Date().toISOString(),
  };
}
