import type { InvestigationClosureNotification } from "@/lib/types";

function normalize(value:string):string{
  return value.trim().toLowerCase().replace(/\s+/g," ");
}

function eventIds(notification:InvestigationClosureNotification):string[]{
  return [...new Set((notification.eventMatches??[]).map((event)=>event.eventId).filter(Boolean))].sort();
}

function autoScope(notification:InvestigationClosureNotification):string{
  const prefix="auto-similar:";
  const suffix=":"+notification.sourceInvestigationId;
  return notification.id.startsWith(prefix)&&notification.id.endsWith(suffix)
    ?notification.id.slice(prefix.length,-suffix.length)
    :"";
}

function sameDecision(
  left:InvestigationClosureNotification,
  right:InvestigationClosureNotification,
):boolean{
  return left.classification===right.classification&&
    normalize(left.reason)===normalize(right.reason)&&
    normalize(left.sourceTitle)===normalize(right.sourceTitle);
}

function sameAutoRecommendation(
  left:InvestigationClosureNotification,
  right:InvestigationClosureNotification,
):boolean{
  if(!left.autoGenerated||!right.autoGenerated||!sameDecision(left,right)) return false;
  const leftEvents=eventIds(left);
  const rightEvents=eventIds(right);
  if(!leftEvents.length||!rightEvents.length||autoScope(left)!==autoScope(right)) return false;
  const leftSet=new Set(leftEvents);
  const rightSet=new Set(rightEvents);
  return leftEvents.every((id)=>rightSet.has(id))||rightEvents.every((id)=>leftSet.has(id));
}

function duplicate(
  left:InvestigationClosureNotification,
  right:InvestigationClosureNotification,
):boolean{
  return left.id===right.id||
    left.sourceInvestigationId===right.sourceInvestigationId||
    sameAutoRecommendation(left,right);
}

function mergeCrossType(
  existing:InvestigationClosureNotification,
  incoming:InvestigationClosureNotification,
):InvestigationClosureNotification{
  const manual=existing.autoGenerated?incoming:existing;
  const newest=incoming.createdAt>=existing.createdAt?incoming:existing;
  const uniqueById=<T extends {id:string}>(values:T[]):T[]=>[
    ...new Map(values.map((item)=>[item.id,item])).values(),
  ];
  const uniqueEvents=(values:NonNullable<InvestigationClosureNotification["eventMatches"]>)=>[
    ...new Map(values.map((item)=>[item.eventId,item])).values(),
  ];
  const matches=uniqueById([...(incoming.matches??[]),...(existing.matches??[])]);
  const representedEventIds=new Set(matches.map((match)=>match.sourceEventId).filter((id):id is string=>Boolean(id)));
  const events=uniqueEvents([...(incoming.eventMatches??[]),...(existing.eventMatches??[])])
    .filter((event)=>!representedEventIds.has(event.eventId));
  return {
    ...manual,
    id:manual.id,
    createdAt:newest.createdAt,
    matches,
    eventMatches:events,
    reviewWarning:incoming.reviewWarning??existing.reviewWarning,
    autoGenerated:false,
  };
}

export function upsertClosureNotification(
  current:InvestigationClosureNotification[],
  incoming:InvestigationClosureNotification,
  replaceSource=false,
):InvestigationClosureNotification[]{
  const sameSource=current.find((item)=>item.sourceInvestigationId===incoming.sourceInvestigationId);
  const sameAuto=current.find((item)=>sameAutoRecommendation(item,incoming));
  const merge=sameSource&&
    !replaceSource&&
    sameSource.autoGenerated!==incoming.autoGenerated&&
    sameDecision(sameSource,incoming);
  const next=merge
    ?mergeCrossType(sameSource!,incoming)
    :sameAuto&&eventIds(sameAuto).length>eventIds(incoming).length
      ?sameAuto
      :incoming;
  return [next,...current.filter((item)=>
    !(replaceSource&&item.sourceInvestigationId===incoming.sourceInvestigationId)&&
    !duplicate(item,incoming),
  )];
}

export function dedupeClosureNotifications(
  notifications:InvestigationClosureNotification[],
):InvestigationClosureNotification[]{
  return notifications.reduce<InvestigationClosureNotification[]>(
    (current,notification)=>upsertClosureNotification(current,notification),
    [],
  );
}
