import assert from "node:assert/strict";
import test from "node:test";
import { dedupeClosureNotifications, upsertClosureNotification } from "../src/lib/notification-dedupe.ts";

function notification({
  id="notice-1",
  sourceInvestigationId="investigation-1",
  sourceTitle="Suspicious outbound connection",
  classification="false_positive",
  reason="Approved scanner traffic.",
  eventIds=["event-1"],
  autoGenerated=false,
  matches=[],
}={}){
  return {
    id,
    createdAt:"2026-10-09T10:00:00.000Z",
    sourceInvestigationId,
    sourceTitle,
    classification,
    reason,
    matches,
    eventMatches:eventIds.map((eventId)=>({eventId,title:"Suspicious outbound connection"})),
    autoGenerated,
  };
}

test("collapses duplicate automatic recommendations from repeated closed investigations",()=>{
  const first=notification({id:"auto-similar:connection:closed-a",sourceInvestigationId:"closed-a",autoGenerated:true});
  const duplicate=notification({id:"auto-similar:connection:closed-b",sourceInvestigationId:"closed-b",autoGenerated:true});
  assert.equal(dedupeClosureNotifications([first,duplicate]).length,1);
});

test("keeps recommendations when their decision or affected event set differs",()=>{
  const original=notification({id:"auto-similar:connection:closed-a",sourceInvestigationId:"closed-a",autoGenerated:true});
  const differentDecision=notification({id:"auto-similar:connection:closed-b",sourceInvestigationId:"closed-b",classification:"high",autoGenerated:true});
  const differentEvent=notification({id:"auto-similar:connection:closed-c",sourceInvestigationId:"closed-c",eventIds:["event-2"],autoGenerated:true});
  assert.equal(dedupeClosureNotifications([original,differentDecision,differentEvent]).length,3);
});

test("keeps the most complete automatic recommendation when another is a subset",()=>{
  const complete=notification({id:"auto-similar:connection:closed-a",sourceInvestigationId:"closed-a",eventIds:["event-1","event-2"],autoGenerated:true});
  const subset=notification({id:"auto-similar:connection:closed-b",sourceInvestigationId:"closed-b",eventIds:["event-1"],autoGenerated:true});
  const [result]=dedupeClosureNotifications([subset,complete]);
  assert.equal(dedupeClosureNotifications([subset,complete]).length,1);
  assert.equal(result.sourceInvestigationId,"closed-a");
  assert.deepEqual(result.eventMatches?.map((event)=>event.eventId),["event-1","event-2"]);
});

test("combines immediate and automatic notices for the same decision into one review item",()=>{
  const immediate=notification({matches:[{id:"investigation-match",sourceEventId:"event-1"}]});
  const automatic=notification({id:"auto-similar:connection:investigation-1",eventIds:["event-1","event-2"],autoGenerated:true});
  const [result]=upsertClosureNotification([immediate],automatic);
  assert.equal(upsertClosureNotification([immediate],automatic).length,1);
  assert.equal(result.autoGenerated,false);
  assert.equal(result.id,immediate.id);
  assert.equal(result.matches.length,1);
  assert.deepEqual(result.eventMatches?.map((event)=>event.eventId),["event-2"]);
});

test("replaces a partially completed review with only the remaining selections",()=>{
  const original=notification({eventIds:["event-1","event-2"]});
  const remaining=notification({id:"notice-2",eventIds:["event-2"]});
  const [result]=upsertClosureNotification([original],remaining,true);
  assert.deepEqual(result.eventMatches?.map((event)=>event.eventId),["event-2"]);
});
